+define+UVM
sv-embed-json/src/json/json_pkg.sv
+incdir+sv-embed-json/src
+incdir+sv-embed-json/src/json
+incdir+sv-embed-json/src/json/uvm
+incdir+src/sv_json_schema/data
+define+JSON_PKG
src/sv_json_schema/data/sv_tb_pkg.sv
+incdir+./
